### ISSUE TITLE
Implement WhatsApp Share

### ISSUE THREAD

**Issue by fmendoza** [fluster/web-social-share#11]
Would be cool :)

**Comment by peterpeterparker** [comment]
Sounds possible, probably like the following https://github.com/720kb/angular-socialshare/blob/1bdd03a2ac96727427e243228c53f4a2778df35f/lib/angular-socialshare.js#L789

That would work only on mobile, then there is the question if it's the work of the web component to handle this or if it's the work of the consumer to provide the info only when mobile...

**Comment by fmendoza** [comment]
I'm using ngx-sharebuttons for <a href="https://trynearme.app">trynearme.app</a> in desktop mode and I think they added a routine to check the platform:

https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/core/src/lib/buttons/whatsapp.ts

See attached image just for reference

<img width="1264" alt="captura de pantalla 2019-01-28 a la s 11 37 59" src="https://user-images.githubusercontent.com/1320696/51854985-be7f7e80-22f1-11e9-8103-5eee4145b084.png">

**Comment by peterpeterparker** [comment]
To detect mobile I've got that too: https://github.com/deckgo/deckdeckgo/blob/916768e96625bdda76922cf39efbb5b4573a41a0/src/components/utils/deckdeckgo-utils.tsx#L80

We could combine that with the link you provided 
https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/core/src/lib/buttons/whatsapp.ts

Ok on it after dinner ;)

**Comment by fmendoza** [comment]
Sweet, let me know if you need help

**Comment by peterpeterparker** [comment]
Actually it seems that nowadays it works find on computer (Mac) and Android devices too with https://api.whatsapp.com/send

Don't have an iPhone with WhatsApp installed, do you have that open @fmendoza ?

could you give a try to https://websocialshare.com ?

P.S.: Implemented but not released but deployed

**Comment by fmendoza** [comment]
@peterpeterparker I can confirm that it works on Mac and Android, but I don't have an iPhone with whatsapp to test it out.

**Comment by peterpeterparker** [comment]
@fmendoza cool thx for the feedback. I'll test on iPhone today, if it works will then release ;)

**Comment by peterpeterparker** [comment]
@fmendoza it worked fine on iPhone but I discovered that it didn't worked in Safari

fortunately found that medium post https://medium.com/@jeanlivino/how-to-fix-whatsapp-api-in-desktop-browsers-fc661b513dc and I didn't know why I didn't went that way straight from the begin ;)

therefore I enhanced the component like the following: 

if mobile -> https://api.whatsapp.com/send?text=Hello
else -> https://web.whatsapp.com/send?text=Hello

thx again for the idea, I gonna release the v4 of this component right now :)
