### ISSUE TITLE
Shadow dom

### ISSUE THREAD

**Issue by peterpeterparker** [fluster/web-social-share#14]
Currently this Web Component isn't shadowed. As I spend several times developing such components recently I'm thinking about migrating this Web Component to a shadowed one.

Reason is also that I noticed yesterday some problems when a none shadowed components would be use in other shadowed components.

Finally, as recently `<slot/>` have been added, these could become the main way to inject actions icon.

Probably something I could develop when I'll implement it DeckDeckGo https://github.com/deckgo/deckdeckgo-starter/issues/30

**Comment by peterpeterparker** [comment]
@fmendoza @abennouna any thoughts or would that be a problem for you?

**Comment by abennouna** [comment]
Nothing that I can think of. Will be glad to upgrade or test!

**Comment by fmendoza** [comment]
Will we have the ability to style the slotted elements from the outside?

**Comment by peterpeterparker** [comment]
@fmendoza I think so, I just read an article about it...which I actually wrote 😂😂😂

https://medium.com/stencil-tricks/a-practical-introduction-to-styling-a-shadow-dom-and-slots-879565a2f423 (chapter "styling slots")

so yep last time I tried out you could style slot from outside, I'll keep that in mind when I'll try to develop this, cool?

**Comment by fmendoza** [comment]
What a great post. Crystal.

Go shadow 😎

**Comment by peterpeterparker** [comment]
@fmendoza @abennouna FYI, it has been release in v5.0.0

this Web Component is now shadowed

https://github.com/fluster/web-social-share/releases/tag/v5.0.0
