### ISSUE TITLE
Failed to load web-social-share.js after update package.json

### ISSUE THREAD

**Issue by fmendoza** [fluster/web-social-share#15]
I think there's an issue with the way of importing this package in Ionic 4.

I can replicate this problem following these steps:

1. Update web-social-share version on package.json
2. Push changes to Netlify
3. App breaks with white screen and an error is logged in console.

Thoughts?

<img width="611" alt="captura de pantalla 2019-02-05 a la s 11 57 43" src="https://user-images.githubusercontent.com/1320696/52294311-966dcc00-293e-11e9-9aa6-ab1f883e688e.png">

**Comment by peterpeterparker** [comment]
@fmendoza something wrong on your side I would say

just tested with http://github.com/fluster/fluster-app/ and I didn't faced any problems

screenshot 2min ago:

<img width="1215" alt="capture d ecran 2019-02-05 a 19 23 05" src="https://user-images.githubusercontent.com/16886711/52295278-b2dc2980-297b-11e9-9ca1-35dbd061a984.png">

**Comment by peterpeterparker** [comment]
@fmendoza some cache issues or something?

**Comment by fmendoza** [comment]
Perhaps cache is causing this issue because if I refresh the page the app loads fine.

I'll investigate.

**Comment by peterpeterparker** [comment]
keep me posted

**Comment by peterpeterparker** [comment]
@fmendoza did you found a solution? could we close that issue?

**Comment by fmendoza** [comment]
@peterpeterparker No luck. I've been busy AF 🤣 Feel free to close for now. I'll reopen if I find out the cause of the issue.

**Comment by peterpeterparker** [comment]
I don't mind keep it open, no worries. Just close it or ping me the day you would have time, no rush, got a lot things going to ;)

**Comment by peterpeterparker** [comment]
@fmendoza I guess we could close that one right, meantime I guess you found a solution or not using it anymore right?

**Comment by fmendoza** [comment]
Yep. It's working fine. Closing now!

**Comment by peterpeterparker** [comment]
awesome @fmendoza  thx for the feedback 👍
