### ISSUE TITLE
Icons not being shown

### ISSUE THREAD

**Issue by Dellos7** [fluster/web-social-share#19]
Hello @peterpeterparker,

I just can't get to show the icons. I'm trying to use the webcomponent in an Ionic/Angular app.

That's how I see the popup:

<img src="https://user-images.githubusercontent.com/11089954/62615759-35837880-b90e-11e9-8d3c-95a343ae5f02.png" alt="image" style="max-width:100%;" width="300px">

Code:
```html
  <web-social-share style="--web-social-share-height: 140px;" [show]="false" [share]="webSocialShareOptions" (closed)="close()" id="wss-{{ index + 1 }}">
      <ion-icon name="logo-facebook" style="font-size:48px" slot="facebook"></ion-icon>
    <ion-icon name="logo-twitter" style="font-size:48px" slot="twitter"></ion-icon>
  </web-social-share>
```

```typescript
this.webSocialShareOptions = {
  displayNames: true,
  config: [{
    facebook: {
      socialShareUrl: 'https://fluster.io'
    }
  },{
    twitter: {
      socialShareUrl: 'https://fluster.io'
    }
  }]
};
```

Was trying the solutions at #10 but I just can't get it working.

Thank you.

David.

**Comment by peterpeterparker** [comment]
@Dellos7 try to add a `display: block` on the `<ion-icon.../>`

```
<ion-icon style="display: block;"/>
```

if that's the solution, sorry, I think it has already been reported but I didn't took the time to add some css in the component or add at least a notice in the documentation

plz let me know if that solves the issue, hope so...

**Comment by Dellos7** [comment]
Hey @peterpeterparker,

Worked like a charm, as well as the webcomponent itself 💃 

You don't have to apologize, this is open source you know, we should say thank you for your great contributions.

Just creating a PR to add this in the readme so it may help anyone else and you don't have to waste time.

<img src="https://user-images.githubusercontent.com/11089954/62617092-5ef1d380-b911-11e9-8368-dadc290f4f8a.png" alt="image" style="max-width:100%;" width="300px">

**Comment by peterpeterparker** [comment]
@Dellos7 happy to hear it worked out and thx a lot for the PR, that's super cool 👍 

I'll merge it later and also modify it a bit, actually the `display=block` is maybe only "mandatory" for `ion-icons`, turns out that if you are for example using font awesome nothing has to be explicity set
