### ISSUE TITLE
Icons are being displayed before rendering the home page.

### ISSUE THREAD

**Issue by srikanthbhamidipalli** [fluster/web-social-share#31]
Social icons are being displayed before loading my site. 
In my react project, I have added your code snippets in the index.html.
`<web-social-share show="false">
         <ion-icon
            name="logo-twitter"
            ...
</web-social-share>`
Could you give me a thought to fix it.

I have taken your blog as reference 
[https://dev.to/daviddalbusco/how-to-implement-the-web-share-api-with-a-fallback-b3](url)

**Comment by peterpeterparker** [comment]
It sounds the Web Component is not imported correctly. How do you import it in your project?

Is your project open source, could you show me some code?

**Comment by srikanthbhamidipalli** [comment]
As my project is not open-source, I have followed the exact steps what you did in your article.
Everything is working fine but the icons were initially displayed before launching the home screen. and after the completion of rendering home page , it's working smooth.

I'm using it in react project, as I put <web-social-share> in index.html, DOM is rendering it even if the `show` prop is false.

**Comment by peterpeterparker** [comment]
I understand, could you maybe then provide a sample repo or Gist?

I don't face this problem in any of my projects but these aren't React projects. I would need some code in order to be able to help otherwise unfortunately I can't.

**Comment by srikanthbhamidipalli** [comment]
Fault is in my side ...

Thank You :+1:
