### ISSUE TITLE
Sending text message along with socialShareUrl.

### ISSUE THREAD

**Issue by srikanthbhamidipalli** [fluster/web-social-share#32]
How to send text message which had been already handled by web share API.
`navigator.share({
      text: 'How to implement the Web Share API and a fallback',
      url: shareUrl,
    });`

And It's very helpful if you provide the list of attributes for services in config.
for example: brandName, socialShareUrl, socialShareBody, socialSharePopupWidth, ..etc

:thinking:

**Comment by peterpeterparker** [comment]
As staten in the README, options are described by its interface https://github.com/peterpeterparker/web-social-share/blob/daa123d61ba7484cf68e76522f22c65fa1ef94d4/src/types/web-social-share/web-social-share-attributes.tsx

That being said, PR are welcomed
