### ISSUE TITLE
Which attribute should I use for sending text in facebook service..

### ISSUE THREAD

**Issue by srikanthbhamidipalli** [fluster/web-social-share#33]
As you have exposed socialShareText for other services except facebook.
Like wise, which attribute should I use for facebook.
I have tried with all facebook services attributes which you have given in types.
But nothing works for me.

Thanks. :+1:

**Comment by peterpeterparker** [comment]
I think it is not possible to share text to Facebook, see [code](https://github.com/peterpeterparker/web-social-share/blob/daa123d61ba7484cf68e76522f22c65fa1ef94d4/src/utils/web-social-share/web-social-share-facebook.tsx)
