### ISSUE TITLE
not able to see text in facebook

### ISSUE THREAD

**Issue by krishnavamsi39** [fluster/web-social-share#35]
I used the attribute socialShareQuote which is mentioned in the types but still I am not able to see the quote

**Comment by peterpeterparker** [comment]
Only applies if `socialShareType === 'share'` 

Check FB doc: https://developers.facebook.com/docs/sharing/reference/share-dialog

And code https://github.com/peterpeterparker/web-social-share/blob/daa123d61ba7484cf68e76522f22c65fa1ef94d4/src/utils/web-social-share/web-social-share-facebook.tsx#L52
