### ISSUE TITLE
Material-UI React Icons not appearing

### ISSUE THREAD

**Issue by absurdprofit** [fluster/web-social-share#40]
I am using Material-UI library in react to supply icons to slots for web-social-share. The share component shows up when I set show={true} prop. But my icons don't appear. Also I'm not able to override any of the styling. The buttons seem to have an outline to them. Help. 🥺
![Screenshot_745](https://user-images.githubusercontent.com/50880261/104268038-fa6d6900-5460-11eb-9608-265195fec037.png)

**Comment by peterpeterparker** [comment]
Did you set `display: block` on the icon as described  if the README?

Can you provide a sample repo to reproduce the issue?

**Comment by absurdprofit** [comment]
No I haven't I'll try that right right now

**Comment by absurdprofit** [comment]
When I set style attributes on the react component they don't appear in the dom. Completely ignored. Same issue in CSS.

**Comment by peterpeterparker** [comment]
A pity. If you can provide a sample repo, I can give it a try this evening.

**Comment by absurdprofit** [comment]
This is the problem code:
![Screenshot_746](https://user-images.githubusercontent.com/50880261/104275767-8091ab80-5471-11eb-8391-0c89109f536c.png)

Index.js:
![Screenshot_747](https://user-images.githubusercontent.com/50880261/104275812-94d5a880-5471-11eb-9090-c485dca7e5d3.png)

**Comment by peterpeterparker** [comment]
- use lower case for the slot names
- try wrap the icons in `div` to which you assign the slot names

**Comment by absurdprofit** [comment]
Changing to lowercase solved it. You should add that to the readme for react. Because I saw upper case. Even in your article you used upper case slot names.

**Comment by absurdprofit** [comment]
In any case thanks a lot. Love the work you're doing. Keep it up mate. Lifesaver ❤.

**Comment by peterpeterparker** [comment]
awesome happy to hear it solved the issue and thx for the positive message 😃

sure, why not updating the readme. can you provide a PR?

**Comment by absurdprofit** [comment]
On it

**Comment by absurdprofit** [comment]
Made the PR. Therefore closing this issue.

**Comment by peterpeterparker** [comment]
Awesome! Thx for the  quick PR @nxtexe 👍
