### ISSUE TITLE
Ability to customize / override rendered names

### ISSUE THREAD

**Issue by abennouna** [fluster/web-social-share#7]
Great component David!

Do you think it's possible to make the brand names customizable?

While it may not make sense for brands, it would at least necessary for "Email" :-)

**Comment by peterpeterparker** [comment]
@abennouna sure Abdelaziz, of course it's possible, you give me one hour?

**Comment by peterpeterparker** [comment]
Done, one hour later ;)

I'll close the feature request once published

**Comment by peterpeterparker** [comment]
Released in v3.0.0

Thx @abennouna for the idea 👍
